POST http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjQ4NTY2NzgsInN1YiI6ImI3Njc1OWIyLWI5ZmQtNDFiNS05OGQyLWQ3OTZlNTMzM2ZlNiJ9.y2OO3ZH7JBbbC896uCI3163S1TIK_r3YUvs8fVcTVhk
Content-Type: application/json

{
  "name": "Meu Produto",
  "price": 100
}

###
GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjQ4NTY2NzgsInN1YiI6ImI3Njc1OWIyLWI5ZmQtNDFiNS05OGQyLWQ3OTZlNTMzM2ZlNiJ9.y2OO3ZH7JBbbC896uCI3163S1TIK_r3YUvs8fVcTVhk

###
GET http://localhost:8000/products/24b35f4c-9831-4992-bcec-0b0d47221130 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjQ4NTY2NzgsInN1YiI6ImI3Njc1OWIyLWI5ZmQtNDFiNS05OGQyLWQ3OTZlNTMzM2ZlNiJ9.y2OO3ZH7JBbbC896uCI3163S1TIK_r3YUvs8fVcTVhk

###
PUT http://localhost:8000/products/24b35f4c-9831-4992-bcec-0b0d47221130 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjQ4NTY2NzgsInN1YiI6ImI3Njc1OWIyLWI5ZmQtNDFiNS05OGQyLWQ3OTZlNTMzM2ZlNiJ9.y2OO3ZH7JBbbC896uCI3163S1TIK_r3YUvs8fVcTVhk
Content-Type: application/json

{
  "name": "Meu Produto Atualizado",
  "price": 150
}

###
DELETE  http://localhost:8000/products/24b35f4c-9831-4992-bcec-0b0d47221130 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjQ4NTY2NzgsInN1YiI6ImI3Njc1OWIyLWI5ZmQtNDFiNS05OGQyLWQ3OTZlNTMzM2ZlNiJ9.y2OO3ZH7JBbbC896uCI3163S1TIK_r3YUvs8fVcTVhk
